
language: android
dist: trusty
android:
  components:
    - tools
    - build-tools-24.0.1
    - android-24
    - platform-tools


#addons:
  #sonarcloud:
   # organization: "thibaultanani-github"
   # token:
     # secure: "f7de74617f4b6c2846327d3af84ae82b8854f43f"
#sudo: false
#script:
 #  - ./gradlew check jacocoTestReport coveralls sendCoverageToCodacy
  #  - bash <(curl -s https://codecov.io/bash)
#  - sonar-scanner
   #- ./gradlew sonarqube

